### ISSUE TITLE
DBT

### ISSUE THREAD

**Issue by jiejiangd** [wuwusky/DBT_Net#2]
您好,我在使用您的代码时效果很差而且跑得速度很慢,不知道您有没有这样的问题

**Comment by wuwusky** [comment]
> 您好,我在使用您的代码时效果很差而且跑得速度很慢,不知道您有没有这样的问题

你好，你也没说清楚你怎么用的，应用在哪，反正在我当前的项目中训练还不错，效果优于resnet-50和efficienNet-b5，至于速度嘛，没察觉到很慢，GPU跑起来没觉得有问题，你可以只用SG和GB模块嘛，论文中也说了这俩可以嵌入到任何现有网络，不必拘泥于一模一样的结构。：）

**Comment by jiejiangd** [comment]
我目前是应用在医学图像分类,网络结构也是resnet所以应该也是正好能用的

**Comment by wuwusky** [comment]
> 我目前是应用在医学图像分类,网络结构也是resnet所以应该也是正好能用的

DL模型的泛化一直不是那么鲁棒，只能祝你调参顺利了~ ：）
